### PR TITLE
gnome 42 support added

### PR DESCRIPTION
**Pull request by mhkarimi1383**
Solves https://github.com/omid/Persian-Calendar-for-Gnome-Shell/issues/95

I have tested things that I can
But I have problem with some font sizes
I thinks that's my problem
Screenshot from 2022-02-20 22-46-31

### CODE REVIEW

**Comment by omid** [comment]
Thanks for the PR.
The week day labels are bigger than usual 🤔 
Also the white box is huge 🙈

**Comment by omid** [comment]
I see it in another way... when it happens to you, it will happen to others.

**Comment by mhkarimi1383** [comment]
My laptop screen is too small, I think I hade such problem before
But it could ve better if others test it too if anyone has gnome 42

**Comment by sttatusx** [comment]
image

**Comment by mhkarimi1383** [comment]
> image

Now that's working :)

**Comment by omid** [comment]
Apparently it's gnome 3.41, isn't it @sttatusx ?

**Comment by sttatusx** [comment]
> Apparently it's gnome 41, isn't it @sttatusx ?

No, it's GNOME 42.beta

**Comment by omid** [comment]
🙈  It's broken for me, too.

Screenshot from 2022-02-23 18-45-51

**Comment by mhkarimi1383** [comment]
That's because of gnome 42 styling changes so I think that's because css code are not responsible 😶
I will try to make it better🤓

**Comment by sttatusx** [comment]
> That's because of gnome 42 styling changes so I think that's because css code are not responsible 😶 I will try to make it better🤓

Thanks!

**Comment by mhkarimi1383** [comment]
found it....
the problem is coming from changes in gnome 42 calendar and we are using `calendar-day-heading`
so I will fix it 

by removing it and creating an alternative class for that

**Comment by mhkarimi1383** [comment]
it has this line inside gnome sources
```css
height: 16px !important;
```

**Comment by mhkarimi1383** [comment]
so what got from our friend's screenshot is that the problem is from vazir font style witch is different from others
also in stylesheets file the comment is important

**Comment by omid** [comment]
@mhkarimi1383 perfect, nice catch 👏🏼 

I would suggest solving it in another way.
The [original css](https://github.com/GNOME/gnome-shell/blob/6b60a189fded722ae37a7d3e94d51a509a7d2df1/data/theme/gnome-shell-sass/widgets/_calendar.scss#L91) reads the data from the gnome theme the user has. So in this case, we will have different format. So it's better not removing the original css class, but just overwriting them.

So my suggestion is to _just_ change the css to this:
```
.pcalendar-weekday .pcalendar-day {
    font-size: 1.1em;
    height: auto;
}
```

**Comment by mhkarimi1383** [comment]
Okay nice suggestion 😃
I will do it

**Comment by mhkarimi1383** [comment]
for me these changes was ok

**Comment by omid** [comment]
@mhkarimi1383 thanks a lot 🙏🏼 
@sttatusx could you also test them in the meanwhile?

Anyway, I'll merge it now.

**Comment by sttatusx** [comment]
> @mhkarimi1383 thanks a lot 🙏🏼 @sttatusx could you also test them in the meanwhile?
> 
> Anyway, I'll merge it now.

Hi Omid,
Honestly, I do not use this extension, but I will leave the screenshot for you anyway.

image

**Pull request merged**
